### ISSUE TITLE
Control updates?

### ISSUE THREAD

**Issue by bigmark641** [bigmark641/SmashTetris#5]
@alangfiles,  Do you think I should change the controls so you can't push/pull with up/down.  Instead up would rotate (in a single direction) and down would drop?

**Comment by alangfiles** [comment]
I really want the controls to eventually be wrapped up in gun-logic. So I think the controls as they are are good, I just want to map them to a portal gun style thing.

**Comment by bigmark641** [comment]
I don't think I understand.  "portal gun style"?

To be clear, my proposal still required shooting the pieces, and the directions would still be relative to the player (not the board).

**Comment by alangfiles** [comment]
Ah, I think we agree?

by portal gun, I just mean 'gun that doesn't shoot bullets'. And yeah, I would like 1 gun that pushes/pulls (regular fire for push, alt fire for pull) and one gun that rotates (both directions, regular fire for clockwise, alternate fire for anticlockwise).

Does that sound like we're talking about the same thing?

**Comment by bigmark641** [comment]
Maybe.  What do you mean by 2 different guns?  Do you mean that you would have to switch weapons and then use the same 2 keys (primary and alt fire) that get different actions?

If so, I was thinking a little differently: the actions "push", "pull", "rotate", and "drop" would be hardcoded to keys (like they are now).  I was just proposing removing the anticlockwise key and remapping the keys so you didn't have to move your hand at all.  I kept finding myself looking down or pressing the wrong rotate.

**Comment by alangfiles** [comment]
Yep, I'm thinking of using 2 different guns, with 2 keys (primary and alt fire). Also, I feel it'd be fun to use the mouse (or a controller), but maybe looking up and down isn't as easy as just looking on a single plane.

But those additions are further down the line, so I think changing it to be more usable with the up/down keys seems good to me.

**Comment by bigmark641** [comment]
Cool, I made the control change, and it nearly feels playable now.  I do like the switching gun idea, from an impracticality standpoint.  Maybe we can made that configurable later (or force it on in "hard").  I feel like the controls are so much more comfortable now.  I do miss the up/down options a bit when you're off to the side though.

Looking up/down is pretty difficult in raycasting.  I was gonna say that in the Wolfenstein 3D style engine (which is what I modeled this after) it is nearly impossible, because it doesn't know how to render the tops/bottoms of things (unlike the super-fancy Doom engine, which has things above/below you at variable heights).  But, on second thought, because everything is at the same level, it might actually be possible (because you can never see the top/bottom of a cube).  Neither Wolfenstein 3D or Doom implemented looking up/down, but that was probably because they implemented sprites (which could only be viewed from one angle).  That being said, I'm not sure how good vanilla javascript's mouse events are, so this may or may not be possible.
