### ISSUE TITLE
Add multiple difficulty options

### ISSUE THREAD

**Issue by bigmark641** [bigmark641/SmashTetris#6]
Options?  Should I drop one of those?

- Easy: Minimap with current piece and player
- Medium: Minimap does not include player
- Hard: Minimap does not include player or piece
- Very hard: No minimap

**Comment by alangfiles** [comment]
I think the difference between Hard and Very Hard doesn't do as much as the other gaps.

I'd drop 'Hard' and just have Very Hard be the 3rd difficulty level.
